# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efef8e304d350c49ef967c3b3085d07726bc2326a081878bd7ccc86a69c34b9b9ae7cd21781734de7eb9227e611163660835d10915c1d229a694a727d28178e0

test:
  secret_key_base: d289953b7d56306eba49a333f21683697a67d090495d37588e437d87cc96b233de831e081b513fc8e21ebf70f3d36c976620427ca3d9a695b4f9a4723b97c8c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
